### ISSUE TITLE
maintainer?

### ISSUE THREAD

**Issue by adamdecaf** [vfaronov/httpheader#2]
Hey @vfaronov!! This library looks really cool, but I'm worried about using it in production code as there's no one watching this repo. Is there an active maintainer? 

Thanks!

**Comment by vfaronov** [comment]
Hi Adam, thanks for your interest. I just wrote this library over the past couple of weeks, so there’s no maintenance history to speak of. However, this isn’t throwaway code, I want it to be useful, and I intend to maintain it. I will love to hear and address any feedback. You can also check the history of another project of mine, [HTTPolice](https://github.com/vfaronov/httpolice).

As for nobody “watching”: I don’t think you have to be “watching” your own repo to get notified — certainly I was notified of this issue — but it turns out I am “watching” all of my other repos, so I’ll be “watching” this one for consistency, too :)

**Comment by vfaronov** [comment]
Seems like I was notified of this issue only because you at-mentioned me. I’m not sure why I wasn’t watching a newly created repo by default. Thanks for reporting this.

**Comment by adamdecaf** [comment]
Sounds great, thanks!
